//
// Created by Ludwig Andreas on 31.07.2023.
//

#ifndef MONITORINGSYSTEM_SRC_MODULES_DUMB_MODULE_DUMB_FUNCS_H_
#define MONITORINGSYSTEM_SRC_MODULES_DUMB_MODULE_DUMB_FUNCS_H_

std::string my_dumb_func();

#endif //MONITORINGSYSTEM_SRC_MODULES_DUMB_MODULE_DUMB_FUNCS_H_
